// CurrentAddress
export const UPDATE_CURRENT_ADDRESS = 'UPDATE_CURRENT_ADDRESS'
export const UPDATE_CURRENT_LAT = 'UPDATE_CURRENT_LAT'
export const UPDATE_CURRENT_LNG = 'UPDATE_CURRENT_LNG'
export const CURRENT_TAG = 'CURRENT_TAG'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'

//Order
export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_PHARM_ID = 'UPDATE_PHARM_ID'
export const RESET = 'RESET'
export const UPDATE_SUBTOTAL = 'UPDATE_SUBTOTAL' 
export const UPDATE_PROMO = 'UPDATE_PROMO' 
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL'
export const TAX_LIST = 'TAX_LIST'
export const UPDATE_DELIVERY_CHARGE = 'UPDATE_DELIVERY_CHARGE' 

//Prescription Order
export const UPDATE_PRESCRIPTION_ID = 'UPDATE_PRESCRIPTION_ID'
export const UPDATE_PRESCRIPTION_DETAILS = 'UPDATE_PRESCRIPTION_DETAILS'
